// Dynamic column configuration based on Lead schema
export const getAvailableColumns = () => {
  const columns = [
    { id: "first_name", label: "First Name", type: "text" },
    { id: "last_name", label: "Last Name", type: "text" },
    { id: "email", label: "Email", type: "text" },
    { id: "phone", label: "Phone", type: "phone" },
    { id: "company", label: "Company", type: "text" },
    { id: "city", label: "City", type: "text" },
    { id: "country", label: "Country", type: "text" },
    { id: "country_code", label: "Country Code", type: "text" },
    { id: "phone_number", label: "Phone Number", type: "phone" },
    { id: "source", label: "Source", type: "dropdown" },
    { id: "campaign_name", label: "Campaign Name", type: "text" },
    { id: "assigned_user", label: "Assigned User", type: "text" },
    { id: "conversion_owner", label: "Conversion Owner", type: "text" },
    { id: "notes", label: "Notes", type: "text" },
    { id: "client_feedback", label: "Client Feedback", type: "text" },
    { id: "dial_attempts", label: "Dial Attempts", type: "number" },
    { id: "no_of_calls", label: "No Of Calls", type: "number" },
    { id: "lead_status", label: "Lead Status", type: "dropdown" },
    { id: "sales_follow_up_datetime", label: "Sales Follow Up Date & Time", type: "datetime" },
    { id: "no_answer_times", label: "No Answer Times", type: "number" },
    { id: "created_date", label: "Created Date & Time", type: "datetime" },
    { id: "updated_date", label: "Update Timestamp", type: "datetime" },
    { id: "last_call_datetime", label: "Last Call Date & Time", type: "datetime" },
    { id: "account_number", label: "Account Number", type: "text" },
    { id: "investor_password", label: "Investor Password", type: "text" },
    { id: "account_status", label: "Account Status", type: "text" },
    { id: "account", label: "Account", type: "text" },
    { id: "deposit_amount_usd", label: "Deposit Amount (USD)", type: "number" },
    { id: "retention_status", label: "Retention Status", type: "text" },
    { id: "retention_follow_up", label: "Retention Follow Up", type: "text" },
    { id: "client_potential", label: "Client Potential", type: "text" },
    { id: "client_deposit_potential", label: "Client Deposit Potential", type: "text" },
    { id: "ftd_datetime", label: "FTD Date & Time", type: "datetime" },
    { id: "ftd_amount", label: "FTD Amount", type: "number" },
    { id: "last_deposit_date", label: "Last Deposit Date", type: "date" },
    { id: "last_deposit_amount", label: "Last Deposit Amount", type: "number" },
    { id: "last_withdrawal_sl", label: "Last Withdrawal Date (SL)", type: "date" },
    { id: "last_withdrawal_utc", label: "Last Withdrawal Date (UTC)", type: "date" },
    { id: "last_withdrawal_amount", label: "Last Withdrawal Amount", type: "number" },
  ];
  return columns;
};